# Generated by Django 4.1.6 on 2023-02-06 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(default=23.0707)),
                ('longitude', models.FloatField(default=80.0982)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimatedDeliveryDate', models.DateTimeField()),
                ('awb_no', models.CharField(max_length=20)),
                ('deliveryNumber', models.IntegerField()),
                ('timeDuration', models.IntegerField()),
                ('loadWeight', models.IntegerField()),
                ('sheetNumber', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='address.location')),
            ],
        ),
    ]
