# Generated by Django 4.1.6 on 2023-02-07 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='calulatedDeliveryDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 21, 19, 3, 955524, tzinfo=datetime.timezone.utc)),
        ),
    ]
